import GlobalContextProvider from "./_providers/contexts/GlobalContextProvider";
import "./globals.css";
import localFont from "next/font/local";
import MUIThemeProvider from "./_providers/MUIThemeProvider";
import CustomModal from "./_components/ui/CustomModal";

export const metadata = {
  title: { template: `%s | سما رایانه`, default: "سما رایانه" },
  description: "Generated by create next app",
};

const vazirmatn = localFont({
  src: [
    {
      path: "../public/fonts/Vazirmatn-FD-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazirmatn-FD-ExtraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazirmatn-FD-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazirmatn-FD-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazirmatn-FD-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazirmatn-FD-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazirmatn-FD-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazirmatn-FD-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazirmatn-FD-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-vazirmatn",
});

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazirmatn?.className} ${vazirmatn?.variable} antialiased text-gray-900 min-h-screen`}
      >
        <MUIThemeProvider>
          <GlobalContextProvider>
            {children}
            <CustomModal />
          </GlobalContextProvider>
        </MUIThemeProvider>
      </body>
    </html>
  );
}
